### ISSUE TITLE
Typo in blog post

### ISSUE THREAD

**Issue by countvajhula** [Bogdanp/setup-racket#34]
Thanks for making this repo! Just reporting a typo in the [linked blog post](https://defn.io/2020/05/05/github-actions-for-racket-revised/) about this repo:

```
+    strategy:
+      matrix:
+        racket-variant: ['BC, 'CS']
+    name: Test on ${{ matrix.racket-variant }} Racket
```
Github complains "You have an error in your yaml syntax"

It's because of a missing closing quote there after `BC`:
```
+        racket-variant: ['BC', 'CS']
```

**Comment by Bogdanp** [comment]
Thanks for the report! This is now fixed.
