### ISSUE TITLE
Issue on macos with stxparam-exptime_rkt.zo

### ISSUE THREAD

**Issue by pmatos** [Bogdanp/setup-racket#4]
I tried using `setup-racket` on `macos` for the first time and I am getting this strange error during my package setup:

```
open-output-file: cannot open output file
  path: /Applications/Racket/collects/racket/compiled/stxparam-exptime_rkt.zo
  system error: Permission denied; errno=13
```

Might be unrelated to `setup-racket` itself but curious to know if you have seen it before. I cannot test this natively as I don't have a macos here so I only see it in actions.
https://github.com/pmatos/racket-loci/runs/591763677?check_suite_focus=true#step:4:30

**Comment by Bogdanp** [comment]
I believe this might be an issue with permissions. What happens if you run `raco pkg install ...` with `sudo`?

**Comment by pmatos** [comment]
Ah interesting - didn't know that we even had `sudo` on macos (complete apple noob here)

Let me give that a go.

**Comment by Bogdanp** [comment]
I think I've fixed the problem on 0.7. Let me know if pinning setup-racket:v0.7 works without sudo.

**Comment by pmatos** [comment]
Giving that a go.

**Comment by pmatos** [comment]
It works - closing.

Thanks for the fast turnaround.

**Comment by Bogdanp** [comment]
Sweet! Thanks for reporting and for putting loci on my radar. I'm excited to play around with it when it's ready, having run into the limitations of places a few times.
