### ISSUE TITLE
`--no-docs` wasn't introduced until 7.9

### ISSUE THREAD

**Issue by LeifAndersen** [Bogdanp/setup-racket#47]
Probably should check if the version is below 7.9 and only include the flag if its at least that version.

**Comment by Bogdanp** [comment]
I dropped that flag circa `v0.12`, so I think if you upgrade to a more recent version (`v1.6.1` is the latest), that should fix the problem.

**Comment by LeifAndersen** [comment]
Ah, good point, thanks. I just copied the code from: https://defn.io/2020/05/05/github-actions-for-racket-revised/

I probably should have read the readme for this repo first...woops. :)

**Comment by Bogdanp** [comment]
It sounds like I need to revise that post again! I'm going to close this now, but let me know if you run into any other problems.
