### ISSUE TITLE
raco unrecognized command: test with path extend

### ISSUE THREAD

**Issue by dannypsnl** [Bogdanp/setup-racket#49]
```
/usr/bin/raco: Unrecognized command: test
```

for reference: https://github.com/failed-dragon-slayer/racket-llvm13/runs/4559310622?check_suite_focus=true

**Comment by Bogdanp** [comment]
I think you need to install `compiler-lib` to get `raco test` in a minimal install.

**Comment by dannypsnl** [comment]
But in my experience that is not required, for reference: https://github.com/racket-tw/k/blob/develop/.github/workflows/test.yml

**Comment by Bogdanp** [comment]
In that case one of your transitive dependencies is bringing `compiler-lib` in: https://github.com/racket-tw/k/runs/4545272166?check_suite_focus=true#step:5:60

**Comment by dannypsnl** [comment]
But then how I install compiler-lib in racket-tw/k but not in failed-dragon-slayer/racket-llvm13? Both of them
1. didn't import compiler-lib
2. use minimal setup

**Comment by Bogdanp** [comment]
Follow the dependency graph here:

https://github.com/racket-tw/k/runs/4545272166?check_suite_focus=true#step:5:284

`racket-doc` depends on `compiler-lib`, something else depends on `racket-doc` and so on. That's what I mean by "transitive dependencies."

**Comment by Bogdanp** [comment]
Also, I think in both cases, you would be much better off not using minimal racket anyway. You're installing many dependencies that you would get "for free" with the regular distribution, so your builds are slower than they could otherwise be.

**Comment by dannypsnl** [comment]
emmm... I get the point.
